---
trainee_workstation_collector:
  ingestion_pipeline:
    interval_minutes: 1
    transports:
      - type: https
        url: https://rep-core.internal/ingest
        token: rep-core-trainee-collector-52f4c918
      - type: syslog
        host: soc-gateway.internal
        port: 514
