---
trainee_workstation_collector:
  ingestion_pipeline:
    interval_minutes: 1
    transports:
      - type: https
        url: https://rep-core.internal/ingest
        token: rep-core-trainee-collector-9c0b4d8f
      - type: syslog
        host: soc-gateway.internal
        port: 514
