---
trainee_workstation_collector:
  ingestion_pipeline:
    interval_minutes: 1
    transports:
      - type: https
        url: https://rep-core.internal/ingest
        token: rep-core-trainee-collector-7b92de11
      - type: syslog
        host: soc-gateway.internal
        port: 514
